FROM ubuntu:14.04

RUN apt-get update; apt-get --force-yes -y install curl 
RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
VOLUME /myfiles:
CMD ["bash"]

# run "docker build . syft"
# might need wsl for below
# docker container run -v $PWD/volume:/myfiles -it syft /bin/bash

# in container:
# syft myfiles/sbom-tool -o spdx-tag-value=myfiles/manifests/sbom-tool.spdx